name: Deploy Github

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1.检出仓库
      - name: Checkout
        uses: actions/checkout@v2

      # 2. 设置pnpm包管理器
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      # 3. 安装nodejs
      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm" # 缓存

      # 4.安装依赖
      - name: Install deps
        run: pnpm install

      # 5.构建/部署
      - name: run deploy_github.sh
        run: |
          pnpm run deploy_github
          pnpm run deploy_github_coding_branch
        env: # 设置环境变量
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
